blog/urls.py
# blog/urls.py 

from django.urls import path 

from . import views 

app_name = "blog"
urlpatterns = [
    path('', views.HomeListView.as_view(), name = 'home'),
    path('post/<int:pk>/', views.BlogDetailView.as_view(), name = 'post_detail' ),
    path('post/create', views.BlogCreateView.as_view(), name = 'post_create'),
    path('post/<int:pk>/edit/', views.BlogUpdateView.as_view(), name = 'post_edit'),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
# blog/models.py 

import datetime

from django.db import models
from django.urls import reverse 
from django.utils import timezone 

class Post(models.Model):

    author = models.ForeignKey(
        'auth.User',
        on_delete = models.CASCADE,
    )

    title = models.CharField(max_length = 200)
    text = models.TextField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:home')

blog/views.py
# blog/views.py

from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, CreateView
from django.http import HttpResponse

from . models import Post


class HomeListView(ListView):
    model = Post 
    template_name = 'home.html'
    context_object_list = 'post_list'

class BlogDetailView(DetailView):
    model = Post 
    template_name  = 'post_detail.html'

class BlogCreateView(CreateView):
    model = Post
    template_name = 'post_create.html'
    fields = '__all__'
    
class BlogUpdateView(UpdateView):
    model = Post 
    template_name = 'post_edit.html'
    fields = ['title', 'text']

templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset = 'utf-8'>
        <title>Test Blog</title> 
    </head>
   
    <body>
        <h1>Test Blog</h1>
        {% block content %}
        {% endblock content %}

    </body>
</html>

templates/home.html
<!-- templates/home.html -->

{% extends 'base.html' %}

{% block content %}
    {% for post in post_list %}
        <h2><a href ="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
        <p>{{ post.text }}</p>
    {% endfor %}

    <p><a href = "{% url 'blog:post_create' %}">+Post</a></p>

{% endblock content %}

templates/post_create.html
<!-- templates/post_create.html -->

{% extends "base.html" %} 

{% block content %}
    <h1>New Post</h1>
    <form action = '' method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type = "submit" value = "Save" />
    </form>
{% endblock content %}

templates/post_detail.html
<!-- templates/post_detail.html -->

{% extends 'base.html' %}

{% block content %}
    <h2>{{ post.title }}</h2>
    <p2>Written by {{ post.author }}</p2>
    <p>{{ post.text }}</p>
    <p>{{ post.pub_date }}</p>

    <p><a href = "{% url 'blog:post_edit' post.pk %}">+Edit</a>
        <a href = "{% url 'blog:home' %}">Back</a>
    </p>
{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit Post</h1>
    <form action = "" method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type = "submit" value ="Update"/>
    </form>
{% endblock content %}